### PR TITLE
Star matching and default orderBy

### PR DESCRIPTION
**Pull request by Jon78**
$model->toSearchableArray() could contain attributes that are not searchable Sphinx-fields, breaking this function. This happens in Laravel Nova together with Scout. The fix is to use star matching, which would give you the same results.

Adapted from https://github.com/DieZeeL/laravel-scout-sphinx/blob/master/src/Engines/SphinxEngine.php

### CODE REVIEW

**Comment by constantable** [comment]
This could be done by overriding toSearchableArray method withing your model
```
    public function toSearchableArray()
    {
        $array = $this->toArray();
        // Customize array...
        return $array;
    }
```

**Comment by Jon78** [comment]
It could, but only for attributes that are searchable. And since you would also want to use Scout for indexing, all Sphinx attributes would have to be defined there, including the ones that are used for filtering (which can’t be used in a match statement).

**Comment by constantable** [comment]
Try to `return []` and sphinx will compile query to `SELECT * FROM ...`

**Comment by constantable** [comment]
Try to `return [];` and query will be compiled to match *

**Comment by Jon78** [comment]
That breaks the update and delete functions.

**Comment by constantable** [comment]
I beleive there is another one way is to add to toSearchableArray() **'*'** value, but I personally do not use RT and can't prove it work seamless in the update method.
OK I'm going to merge. Thanks for PR!

**Pull request merged**
